### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ComtradeRecord'

### ISSUE THREAD

**Issue by Skucul** [miguelmoreto/pycomtrade#15]
I'm trying start using pyComtrade but example 3 crash. I used Python 3.4.4 [MSC v.1600 32 bit (Intel)] on win32

**Comment by ldemattos** [comment]
@Skucul , hi!

 pyComtrade is developed with python2. Please, give a try with this version.

Best regards.

**Comment by Skucul** [comment]
I converted pyComtrade.py  (2to3 tool) and now is working!

**Comment by Gseguelg** [comment]
@Skucul can you make a pull request about that?

I found same problem under linux for Python 3.6.8 (installed by pip):
`
>>> import pyComtrade
>>> comtradeObj = pyComtrade.ComtradeRecord('./test_data3/test3.cfg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyComtrade' has no attribute 'ComtradeRecord'
`
