### ISSUE TITLE
Lacks write example or documentation

### ISSUE THREAD

**Issue by LFBJC** [miguelmoreto/pycomtrade#20]
Hello, sorry I searched for a documentation here and on the website https://pypi.org/project/pyComtrade/ but I found no documentation for it. I looked at the code and saw the example, but it's an example of how to read comtrade files; the description says it's intended to read and write comtrade files, but by looking at the code I couldn't figure out how to write them.

**Comment by miguelmoreto** [comment]
Hello @LFBJC ! Yes, the module is intended to also write Comtrade, but this functionality is not implemented yet. I've not had time to work on this project lately, thus the documentation is also not done yet. Please note that the module on the PyPI page is significantly outdated in comparison with the code here on Github.

**Comment by LFBJC** [comment]
ok then, thanks

**Comment by miguelmoreto** [comment]
I was able to update the readme text (to clarify that the write function is not implemented) and genearated a new and upated PyPI package.
Best regards!
