### ISSUE TITLE
Problems with *.cfg with frequency and sample rate as floats

### ISSUE THREAD

**Issue by ldemattos** [miguelmoreto/pycomtrade#6]
The .cfg file that I'm attempting to read has the frequency and sample rate data as:

> 60.000000000
> 1
> 15360.000000000,42240

Then, when I try to read it, I get:

> pyComtrade instance created!
> Traceback (most recent call last):
>   File "example1_l.py", line 44, in <module>
>     comtradeObj = pyComtrade.ComtradeRecord(dataFile)
>   File "/home/leonardo/projects/pycomtrade/src/pyComtrade.py", line 105, in __init__
>     self.ReadCFG()
>   File "/home/leonardo/projects/pycomtrade/src/pyComtrade.py", line 210, in ReadCFG
>     self.lf = int(self.filehandler.readline())
> ValueError: invalid literal for int() with base 10: '60.000000000\r\n'

I already have a proposition that I will submit as pull request.

**Comment by miguelmoreto** [comment]
Is this .cfg compliant with the standard? I had to check the newer comtrade standard but I think that this is a problem with the device that generates your .cfg. This field should be an integer. I don't know if we should deal with non standard cfg file (unless this is supported in the last version of standard).

Best regards!

**Comment by ldemattos** [comment]
Hey, @miguelmoreto!

I don't know if this cfg file is compliant and I don't have further informations about the recorder device. Sorry.

Anyhow, I do agree with you that we should stick to IEEE standard, however the proposed solution is so simple and don't harm the reading of a cfg file have the frequency field/sample rate as integers that I don't see it as a problem.

Best regards,

**Comment by miguelmoreto** [comment]
I accepted your PR. Thanks!
best regards!

**Comment by ldemattos** [comment]
Glad to help!
Best regards.
